pipeline {
    agent any

    environment {
        OS_SSH_KEY = credentials('OS_SSH_KEY')
        GIT_SSH_CREDS =  credentials('GIT_SSH_CREDS')
    }

    stages {
        stage('Get instance IP') {
            steps {
                script {
                    echo 'Attempting to copy artifacts from InfraCreation job...'
                    // Copy the instance_ip.txt file from the previous job
                    copyArtifacts(
                            projectName: 'TramshedTechProject_InfraCreation',
                            filter: 'instance_ip.txt',
                            target: 'artifacts',
                            selector: lastSuccessful()
                    )
                    echo 'Artifacts copied. Reading instance IP...'
                    env.INSTANCE_IP = readFile('artifacts/instance_ip.txt').trim()
                    sh 'echo "Instance IP: $INSTANCE_IP"'
                }
            }
        }
        stage('Clone Project ') {
            steps {
                script {
                    sh 'echo "SSH into newly created instance"'
                    sh 'echo "clone the project"'
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    // build commands
                    sh 'echo "Build Project"'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // test and test report commands
                    sh 'echo "Test Project"'
                }
            }
        }
        stage('Run Project') {
            steps {
                script {
                    // Run project
                    sh 'echo "Run Project"'
                }
            }
        }
    }
}