pipeline {
    agent any


    stages {
        stage('Terraform Apply') {
            steps {
                script {

//                     sh 'source openrc.sh'
//                     Initialize and apply Terraform
//                     sh 'terraform init -input=false'
//                     sh 'terraform apply -auto-approve'
                    sh 'echo Building in ${WORKSPACE}'
                    sh 'echo "This is working"'
                }
            }
        }
        stage('Install java and gradle'){
            steps{
                script {
                    sh 'echo "Install Java and Gradle after infra creation"'
                    // Install Java
                    sh '''
                        echo "Installing Java"
                        sudo apt-get update
                        sudo apt-get install -y openjdk-17-jdk
                        java -version
                    '''

                    // Install Gradle
                    sh '''
                        echo "Installing unzip and Gradle"
                        sudo apt-get install -y wget unzip
                        wget https://services.gradle.org/distributions/gradle-8.0-bin.zip
                        sudo mkdir /opt/gradle
                        sudo unzip -d /opt/gradle gradle-8.0-bin.zip
                        echo "export PATH=\$PATH:/opt/gradle/gradle-8.0/bin" >> ~/.bash_profile
                        source ~/.bash_profile
                        gradle -v
                    '''
                }
            }
        }
    }
    post {
        success {
            script {
//                 Trigger the Build and Run Project pipeline
                build job: 'TramshedTechProject_Deployment', wait: false
                sh  'echo "This too"'
            }
        }
    }
}