pipeline {
    agent any

    environment {
        OS_PASSWORD = credentials('openstackpass_nithin')
        OS_SSH_KEY = credentials('OS_SSH_KEY')
    }

    stages {
        stage('Create Infra') {
            steps {
                script {
                    dir("${WORKSPACE}/Deployment/Infracreation/Terraform/") {
                        sh '''
                            ls
                            pwd
                            chmod +x GROUP-1-TGD-2425-openrc.sh
                            source ${PWD}/GROUP-1-TGD-2425-openrc.sh

                            terraform init -input=false
                            terraform plan
                            terraform apply -auto-approve
                        '''
                        env.INSTANCE_IP = sh(script: "terraform output -raw instance_ip", returnStdout: true).trim()
                    }
                }
            }
        }

        stage('Check Instance Readiness') {
            steps {
                script {
                    if (env.INSTANCE_IP) {
                        // Retry mechanism to check instance readiness
                        timeout(time: 2, unit: 'MINUTES') {
                            waitUntil {
                                def ready = sh(script: "ssh -i $OS_SSH_KEY -o StrictHostKeyChecking=no rocky@${INSTANCE_IP} 'echo ready'", returnStatus: true) == 0
                                return ready
                            }
                        }
                    } else {
                        error "Instance IP is not available."
                    }
                }
            }
        }

        stage('Install java and gradle'){
            steps{
                script {
                    sh 'echo "Install Java and Gradle after infra creation"'
                    // Install Java
                    sh '''
                        echo "Installing Java"
                        sudo apt-get update
                        sudo apt-get install -y openjdk-17-jdk
                        java -version
                    '''

                    // Install Gradle
                    sh '''
                        echo "Installing unzip and Gradle"
                        sudo apt-get install -y wget unzip
                        wget https://services.gradle.org/distributions/gradle-8.0-bin.zip
                        sudo mkdir /opt/gradle
                        sudo unzip -d /opt/gradle gradle-8.0-bin.zip
                        echo "export PATH=\$PATH:/opt/gradle/gradle-8.0/bin" >> ~/.bash_profile
                        source ~/.bash_profile
                        gradle -v
                    '''
                }
            }
        }
    }
    post {
        success {
            script {
//                 Trigger the Build and Run Project pipeline
                build job: 'TramshedTechProject_Deployment', wait: false
                sh  'echo "This too"'
            }
        }
    }
}